version: "3.9"  
services:
  app:
    build: . # build the Docker image 
    container_name: amonycoffee-new
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8080:80"
    depends_on:
      - db
    
  db:
    image: "keinos/sqlite3:latest"
    container_name: amonycoffee_db
