name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Build .NET project
        run: dotnet build --configuration Release
        continue-on-error: false

  build-docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker
        run: sudo service docker start

      - name: Build Docker image
        run: |
          docker build -t amonycoffee-new:latest .
      # Azure Container Registry Login
          az acr login -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }} amonycoffeeregistry.azurecr.io
          docker tag amonycoffee-new amonycoffeeregistry.azurecr.io/amonycoffeeregistry:latest
          docker push amonycoffeeregistry.azurecr.io/amonycoffeeregistry:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        run: |
          az webapp config container set --name amonycoffee --resource-group Amonycoffee --docker-custom-image-name amonycoffeeregistry.azurecr.io/amonycoffee-new:latest
