name: Build and Deploy

on:
  push:
    branches:
      - dev  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x  

      - name: Build .NET project
        run: dotnet build --configuration Release
        continue-on-error: false

  build-docker:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image with BuildKit
        run: |
          export DOCKER_BUILDKIT=1
          docker build -t amonycoffee-new:latest .