name: Build and Deploy

on:
  push:
    branches:
      - dev  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x  

      - name: Build .NET project
        run: dotnet build --configuration Release
        continue-on-error: false

  build-docker:
    runs-on: ubuntu-latest
    # ensure the build has been successful before proceed to build docker
    needs: build
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker
        run: sudo service docker start

      # - name: Set up Docker BuildKit
      #   run: |
      #     export DOCKER_BUILDKIT=1
      #   shell: bash

      - name: Build Docker image
        run: |
          docker build -t amonycoffee-new:latest .
        # env:
        #   DOCKER_BUILDKIT: 1